/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car_parking_escape.gui;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import car_parking_escape.Map;
import car_parking_escape.Move;
import car_parking_escape.ai.Tree;

/**
 *
 * @author armin
 */
public class JFrameMain extends javax.swing.JFrame {

    //
    private int squareSize = 50;
    private int jPanelGameSize = 120;
    //
    private Color[] staticColors = {
        Color.RED,
        Color.BLUE,
        Color.GREEN,
        Color.YELLOW,
        Color.MAGENTA,
        Color.CYAN,
        Color.PINK
    };
    private Color[] colors;
    //
    private JPanel jPanelGame;
    private JPanel[][] jPanels;
    private JLabel[][] jLabels;
    //
    private int[][] vehicleMatrix;
    private Point doorPoint;

    /**
     * Creates new form NewJFrame
     */
    public JFrameMain() {
        initComponents();
        setLocationCenter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldMapRows = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMapColumns = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldVehicleNumbers = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Parking Escape");
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabel1.setText("Map Rows:");

        jTextFieldMapRows.setText("6");

        jLabel2.setText("Map Columns:");

        jTextFieldMapColumns.setText("6");

        jLabel3.setText("Vehicle Numbers:");

        jTextFieldVehicleNumbers.setText("5");

        jLabel4.setText("Debug Mode:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Move Delay:");

        jSlider1.setMaximum(20);
        jSlider1.setValue(3);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel6.setText("3 seconds");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldMapColumns)
                                .addComponent(jTextFieldMapRows)
                                .addComponent(jTextFieldVehicleNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jButton1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldMapRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldMapColumns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldVehicleNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card2");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(java.awt.Color.gray);
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 120));

        jComboBox2.setMinimumSize(new java.awt.Dimension(170, 28));
        jComboBox2.setPreferredSize(new java.awt.Dimension(170, 28));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jButton2.setText("Change Color");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Parking Door");
        jRadioButton2.setEnabled(false);

        jButton3.setText("Do it!");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButton2))
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)))
                .addGap(7, 7, 7)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        getContentPane().add(jPanel2, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int map_rows = Integer.parseInt(jTextFieldMapRows.getText());
        int map_columns = Integer.parseInt(jTextFieldMapColumns.getText());
        int vehicle_numbers = Integer.parseInt(jTextFieldVehicleNumbers.getText());
        boolean debug = jComboBox1.getSelectedItem().toString().equals("Yes");

        // 
        vehicleMatrix = new int[map_rows][map_columns];
        for (int i = 0; i < map_rows; i++) {
            for (int j = 0; j < map_columns; j++) {
                vehicleMatrix[i][j] = -1;
            }
        }

        // vehicle color list
        colors = new Color[vehicle_numbers];
        for (int i = 0; i < vehicle_numbers; i++) {
            if (i < staticColors.length) {
                colors[i] = staticColors[i];
            } else {
                colors[i] = RandomColor();
            }
        }

        // vehicle combobox list
        String[] string_vehicles = new String[vehicle_numbers + 1];
        string_vehicles[0] = "Clear";
        for (int i = 1; i < vehicle_numbers + 1; i++) {
            if (i == 1) {
                string_vehicles[i] = "Vehicle " + i + " (Escape Car)";
            } else {
                string_vehicles[i] = "Vehicle " + i;
            }
        }
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(string_vehicles));
        jComboBox2.setSelectedIndex(1);

        // jpanel game
        jPanelGame = new JPanel();
        jPanelGame.setLayout(new GridLayout(map_rows, map_columns));
        jPanelGame.setSize(map_rows * squareSize, map_columns * squareSize);
        jPanels = new JPanel[map_rows][map_columns];
        jLabels = new JLabel[map_rows][map_columns];
        for (int i = 0; i < map_rows; i++) {
            for (int j = 0; j < map_columns; j++) {
                JLabel jLabel = new JLabel();
                jLabel.setHorizontalAlignment(SwingConstants.CENTER);
                jLabel.setVerticalAlignment(SwingConstants.CENTER);
                jLabel.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
                jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        int x = -1;
                        int y = -1;
                        for (int i = 0; i < jLabels.length; i++) {
                            for (int j = 0; j < jLabels[0].length; j++) {
                                if (jLabels[i][j] == jLabel) {
                                    x = i;
                                    y = j;
                                }
                            }
                        }

                        if (buttonGroup1.isSelected(jRadioButton1.getModel())) {
                            if (jComboBox2.getSelectedIndex() == 0) {
                                vehicleMatrix[x][y] = -1;
                            } else {
                                int vehicle = Integer.parseInt(jComboBox2.getSelectedItem().toString().split(" ")[1]) - 1;
                                vehicleMatrix[x][y] = vehicle;
                            }
                            updateGame();
                        } else {
                            if (((x == 0 || x == map_rows - 1) && (y > 0 && y < map_columns - 1))
                                    || ((y == 0 || (y == map_columns - 1)) && (x > 0 && x < map_rows - 1))) {
                                if (doorPoint != null) {
                                    jLabels[doorPoint.x][doorPoint.y].setIcon(null);
                                }
                                doorPoint = new Point(x, y);
                                ImageIcon imageIcon;
                                if (x == 0) {
                                    imageIcon = new ImageIcon(getClass().getResource("/image/up45.png"));
                                } else if (x == map_rows - 1) {
                                    imageIcon = new ImageIcon(getClass().getResource("/image/down45.png"));
                                } else if (y == 0) {
                                    imageIcon = new ImageIcon(getClass().getResource("/image/left45.png"));
                                } else {
                                    imageIcon = new ImageIcon(getClass().getResource("/image/right45.png"));
                                }
                                jLabels[doorPoint.x][doorPoint.y].setIcon(imageIcon);
                            }
                        }
                    }
                });
                jLabels[i][j] = jLabel;

                jPanels[i][j] = new JPanel();
                jPanels[i][j].setLayout(new GridLayout(1, 1));

                jPanels[i][j].add(jLabels[i][j]);
                jPanelGame.add(jPanels[i][j]);
            }
        }
        jPanel2.add(jPanelGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, jPanelGameSize, map_rows * squareSize, map_columns * squareSize));

        // set frame size and location
        int max = Math.max(jPanel4.getWidth(), map_columns * squareSize);
        this.setSize(this.getInsets().left + this.getInsets().right + (max),
                this.getInsets().top + this.getInsets().bottom + (map_rows * squareSize + jPanelGameSize));
        this.setLocationCenter();

        CardLayout cardLayout = (CardLayout) getContentPane().getLayout();
        cardLayout.show(jPanel2.getParent(), "card3");

        updateGame();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int vehicle = Integer.parseInt(jComboBox2.getSelectedItem().toString().split(" ")[1]) - 1;
        Color new_color = JColorChooser.showDialog(null, "Choose a color", colors[vehicle]);
        if (new_color != null) {
            colors[vehicle] = new_color;
            updatejButton2Background();
            updateGame();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        updatejButton2Background();
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            int vehicle_numbers = Integer.parseInt(jTextFieldVehicleNumbers.getText());
            Map map = new Map(vehicleMatrix, vehicle_numbers);

            Thread thread = new Thread() {
                public void run() {
                    try {
                        Tree tree = new Tree(map);
                        tree.start();
                        ArrayList<Move> moves = tree.getMoves();
                        for (int i = 0; i < moves.size(); i++) {
                            map.moveVehicle(moves.get(i));
                            vehicleMatrix = map.getMatrix();
                            updateGame();
                            Thread.sleep(jSlider1.getValue() * 1000);
                        }
                        JOptionPane.showMessageDialog(null, "Your car escape is ready!");
                    } catch (Exception exception) {
                        exception.printStackTrace();
                        JOptionPane.showMessageDialog(null, exception.getMessage());
                    }
                }
            };
            thread.start();

        } catch (Exception exception) {
            JOptionPane.showMessageDialog(null, exception.toString());
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        jLabel6.setText(jSlider1.getValue() + " seconds");
    }//GEN-LAST:event_jSlider1StateChanged

    private void setLocationCenter() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;
        this.setLocation(x, y);
    }

    private Color RandomColor() {
        int r = ThreadLocalRandom.current().nextInt(0, 255);
        int g = ThreadLocalRandom.current().nextInt(0, 255);
        int b = ThreadLocalRandom.current().nextInt(0, 255);
        Color color = new Color(r, g, b);
        return color;
    }

    private void updatejButton2Background() {
        if (jComboBox2.getSelectedIndex() == 0) {
            jButton2.setBackground(Color.WHITE);
        } else {
            int vehicle = Integer.parseInt(jComboBox2.getSelectedItem().toString().split(" ")[1]) - 1;
            jButton2.setBackground(colors[vehicle]);
        }
    }

    private void updateGame() {
        for (int i = 0; i < jPanels.length; i++) {
            for (int j = 0; j < jPanels[0].length; j++) {
                if (vehicleMatrix[i][j] == -1) {
                    jPanels[i][j].setBackground(Color.WHITE);
                    jLabels[i][j].setText("");

                } else {
                    jPanels[i][j].setBackground(colors[vehicleMatrix[i][j]]);
                    jLabels[i][j].setText((vehicleMatrix[i][j] + 1) + "");
                }
            }
        }
        this.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextFieldMapColumns;
    private javax.swing.JTextField jTextFieldMapRows;
    private javax.swing.JTextField jTextFieldVehicleNumbers;
    // End of variables declaration//GEN-END:variables
}
